### ISSUE TITLE
wmd-buttons path

### ISSUE THREAD

**Issue by AlexP11223** [rtfb/pagedown-editor#2]
Why did you specify buttons image path as `/static/wmd-buttons.png`? Isn't it better to leave it as just `wmd-buttons.png` so we could use any folder name instead of `static`?

**Comment by rtfb** [comment]
That particular instance must be an oversight when extracting this thing from my website. But how would omission of `/static/` solve the problem? It would still be a hardcoded path in css.

**Comment by AlexP11223** [comment]
If it is `wmd-buttons.png` (relative path) then I can copy these 2 files to any folder I want such as `/pagedown/`, `/assets/pagedown/`, ...

**Comment by rtfb** [comment]
That makes sense, thanks! Pushed a fix and published.
